### ISSUE TITLE
Implicit solve requires yaml-cpp

### ISSUE THREAD

**Issue by drryjoh** [drryjoh/chemgen#8]
brew install yaml-cpp

**Comment by drryjoh** [comment]
right now it isn't as easy as a -lyamp-cpp flag or whatever. May need to think about yaml as third party, or a yaml library option

**Comment by drryjoh** [comment]
@ericjching I changed it so the `configuration.yaml` file changes:

```
build:
  chemgen_smp: None 
  chemgen_input: "-lyaml-cpp"
  chemgen_optimized: O2
```

You can now change to 
```
build:
  chemgen_smp: None 
  chemgen_input: "-L/path/to/lib -I/path/to/include -lyaml-cpp"
  chemgen_optimized: O2
```
